packages:
  - apps/*
  - packages/*
allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': true
  argon2: true
  esbuild: true
  prisma: true
  sharp: true
overrides:
  sharp: 0.35.3
  postcss: 8.5.25
  fast-uri: 3.1.5
  '@nestjs/swagger>js-yaml': 5.2.3
